name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          if [ -f version.txt ]; then
            echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    name: Trigger Amplify Deployment
    needs: release
    if: ${{ needs.release.outputs.version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            'https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=491b16b6-4c4b-4690-ba80-3e4dcf40a4d4&token=HoP06RMo7z7VPwCznlDYrfSHdqBcPTCnMWgEybr9A'
