name: Create Release and Deploy to Staging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    outputs:
      released: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.semantic.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release and extract version
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_OUTPUT=$(npx semantic-release || true)

          echo "$RELEASE_OUTPUT"

          if echo "$RELEASE_OUTPUT" | grep -q "Published release"; then
            version=$(echo "$RELEASE_OUTPUT" | grep -oP 'Published release \K([0-9]+\.[0-9]+\.[0-9]+)')
            echo "Published version: $version"
            echo "released=true" >> "$GITHUB_OUTPUT"
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            echo "No new version published."
            echo "released=false" >> "$GITHUB_OUTPUT"
          fi

  deploy-staging:
    name: Deploy to Amplify (Staging)
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Amplify Staging webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            'https://webhooks.amplifyuif.us-east-1.amazonaws.com/prod/webhooks?id=491b16b6-4c4b-4690-ba80-3e4dcf40a4d4&token=HoP06RMo7z7VPwCznlDYrfSHdqBcPTCnMWgEybr9A'
